# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liquid Twitter Timeline
description: >- # this means to ignore newlines until "baseurl:"
  Liquid _plugin_ for embeding Twitter Timelines within GitHub Pages.
# baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://liquid-utilities.github.io'
author: S0AndS0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


## Enabled to publish future dated content
future: true


## Thanks be to - https://stackoverflow.com/a/45870924/2632107
##  for the following sweat bits
# sass:
#   load_paths:
#     - _sass
#     - _scss


## Thanks be to - https://jekyllrb.com/docs/collections/
# collections_dir: timeline_examples
# collections:
#   twitter_timelines:
#     output: true
#     permalink: /:collection/:name/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
